/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.slf4j.LoggerFactory;

import static org.junit.Assert.*;

// Reference: https://github.com/qos-ch/logback/blob/v_1.6.3/logback-classic/src/test/java/ch/qos/logback/classic/LoggerTest.java
public class LogOutputTest {
    private final Logger logger = (Logger) LoggerFactory.getLogger(App.class);

    private final ListAppender<ILoggingEvent> appender = new ListAppender<>();

    @Before
    public void attachAppender() {
//        appender.setContext(logger.getLoggerContext());
        appender.start();
        logger.addAppender(appender);
    }

    @After
    public void detachAppender() {
        logger.detachAppender(appender);
        appender.stop();
    }

    @Test
    public void appLogsGreeting() {
        App.main(new String[0]);

        assertEquals(1, appender.list.size());
        ILoggingEvent event = appender.list.get(0);
        assertEquals(Level.INFO, event.getLevel());
        assertEquals("Hello World!", event.getFormattedMessage());
    }
}
